version: '3.8'
name: ims

services:
  products_postgres:
    image: postgres:14.5
    container_name: products_postgres
    restart: always
    environment:
      - POSTGRES_DB=products
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    ports:
      - "5701:5432"
    volumes:
      - pg-data:/var/lib/postgresql/data

  products_redis:
    image: redis:latest
    container_name: products_redis
    restart: always
    ports:
      - "5702:6379"

volumes:
  pg-data:
    driver: local
