version: '3.8'
name: ims

services:
  inventory_postgres:
    image: postgres:14.5
    container_name: inventory_postgres
    restart: always
    environment:
      - POSTGRES_DB=inventory
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    ports:
      - "5701:5432"
    volumes:
      - pg-data:/var/lib/postgresql/data

volumes:
  pg-data:
    driver: local
